# Generated by Django 3.2.12 on 2022-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='roll_no',
        ),
        migrations.AlterField(
            model_name='stu',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
