# Generated by Django 3.2.12 on 2022-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220203_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
